import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1781796101259 implements MigrationInterface {
    name = 'InitialSchema1781796101259'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE TABLE "equipment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, CONSTRAINT "UQ_b44a87bec78c8cf13f5bb838577" UNIQUE ("name"), CONSTRAINT "PK_0722e1b9d6eb19f5874c1678740" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "program_day_exercises" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "program_day_id" uuid NOT NULL, "exercise_id" uuid NOT NULL, "order" integer NOT NULL DEFAULT '1', "target_sets" integer NOT NULL DEFAULT '3', "target_reps_range" character varying NOT NULL DEFAULT '8-12', "target_rest_time" integer NOT NULL DEFAULT '90', CONSTRAINT "PK_dec71463cd0c83026cc1e002e57" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "program_days" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "program_id" uuid NOT NULL, "day_number" integer NOT NULL, "title" character varying NOT NULL, CONSTRAINT "PK_cff1cb768e103fd904e79baf3e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."programs_level_enum" AS ENUM('beginner', 'intermediate', 'advanced')`);
        await queryRunner.query(`CREATE TABLE "programs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "level" "public"."programs_level_enum" NOT NULL DEFAULT 'beginner', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d43c664bcaafc0e8a06dfd34e05" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."profiles_goal_enum" AS ENUM('gain_muscle', 'lose_fat', 'stay_active', 'athletic', 'fat_loss', 'hypertrophy', 'strength', 'endurance')`);
        await queryRunner.query(`CREATE TYPE "public"."profiles_fitness_level_enum" AS ENUM('beginner', 'intermediate', 'advanced')`);
        await queryRunner.query(`CREATE TYPE "public"."profiles_equipment_access_enum" AS ENUM('gym', 'home', 'none')`);
        await queryRunner.query(`CREATE TABLE "profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "goal" "public"."profiles_goal_enum" NOT NULL DEFAULT 'stay_active', "age" integer, "gender" character varying, "weight" numeric(5,2), "height" numeric(5,2), "training_days" integer, "training_location" character varying, "daily_calories" integer, "daily_protein" integer, "daily_water" integer, "daily_steps" integer, "current_program_id" uuid, "body_fat_percentage" numeric(5,2), "fitness_level" "public"."profiles_fitness_level_enum" NOT NULL DEFAULT 'beginner', "days_per_week_available" integer NOT NULL DEFAULT '3', "session_duration_minutes" integer NOT NULL DEFAULT '60', "equipment_access" "public"."profiles_equipment_access_enum" NOT NULL DEFAULT 'gym', "injuries" jsonb NOT NULL DEFAULT '[]', "preferences" character varying, CONSTRAINT "REL_9e432b7df0d182f8d292902d1a" UNIQUE ("user_id"), CONSTRAINT "PK_8e520eb4da7dc01d0e190447c8e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "password" character varying, "name" character varying, "avatar_url" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "workout_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "program_day_id" uuid, "date" date NOT NULL DEFAULT ('now'::text)::date, "duration" integer, "completed" boolean NOT NULL DEFAULT false, "status" character varying NOT NULL DEFAULT 'active', "rpe" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_eea00e05dc78d40b55a588c9f57" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "exercise_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workout_session_id" uuid NOT NULL, "exercise_id" uuid NOT NULL, "sets" jsonb NOT NULL DEFAULT '[]', "reps" integer, "weight" numeric(5,2), "one_rep_max" numeric(5,2), "rpe" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_32076bf978e4169be16e25bf8dc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "muscle_groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, CONSTRAINT "UQ_7b67dd7f791008ed1532e76a9c4" UNIQUE ("name"), CONSTRAINT "PK_87e03ee9f78be5d7a7d0e08897e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."exercises_difficulty_enum" AS ENUM('beginner', 'intermediate', 'advanced')`);
        await queryRunner.query(`CREATE TYPE "public"."exercises_source_enum" AS ENUM('internal', 'exercicedb', 'wger')`);
        await queryRunner.query(`CREATE TABLE "exercises" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "display_name" character varying, "description" text, "difficulty" "public"."exercises_difficulty_enum" NOT NULL DEFAULT 'beginner', "instructions" jsonb NOT NULL DEFAULT '[]', "gif_url" character varying, "video_url" character varying, "source" "public"."exercises_source_enum" NOT NULL DEFAULT 'internal', "external_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "muscle_group_id" uuid, "equipment_id" uuid, CONSTRAINT "UQ_a521b5cac5648eedc036e17d1bd" UNIQUE ("name"), CONSTRAINT "PK_c4c46f5fa89a58ba7c2d894e3c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."nutrition_logs_mealtype_enum" AS ENUM('breakfast', 'lunch', 'dinner', 'snack')`);
        await queryRunner.query(`CREATE TABLE "nutrition_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "food_id" uuid NOT NULL, "date" date NOT NULL DEFAULT ('now'::text)::date, "mealType" "public"."nutrition_logs_mealtype_enum" NOT NULL, "quantity" numeric(6,2) NOT NULL DEFAULT '1', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_dd9d41be1c628a937e0faceb41b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."foods_source_enum" AS ENUM('database', 'user', 'ai')`);
        await queryRunner.query(`CREATE TABLE "foods" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "barcode" character varying, "source" "public"."foods_source_enum" NOT NULL DEFAULT 'database', "user_id" uuid, "calories" numeric(6,2) NOT NULL, "protein" numeric(5,2) NOT NULL DEFAULT '0', "carbs" numeric(5,2) NOT NULL DEFAULT '0', "fat" numeric(5,2) NOT NULL DEFAULT '0', "serving_size" numeric(6,2) NOT NULL DEFAULT '100', "serving_unit" character varying NOT NULL DEFAULT 'g', "image_url" character varying, CONSTRAINT "UQ_94919a5b0af8952c73beb42fbc9" UNIQUE ("barcode"), CONSTRAINT "PK_0cc83421325632f61fa27a52b59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "workout_exercises" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workout_plan_id" uuid NOT NULL, "exercise_id" uuid NOT NULL, "sets" integer NOT NULL DEFAULT '3', "reps" character varying NOT NULL, "weight" numeric(5,2), "rest_time_seconds" integer NOT NULL DEFAULT '90', "order_index" integer NOT NULL DEFAULT '0', "day_number" integer NOT NULL DEFAULT '1', CONSTRAINT "PK_377f9ead6fd69b29f0d0feb1028" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."workout_plans_goal_enum" AS ENUM('fat_loss', 'hypertrophy', 'strength', 'endurance')`);
        await queryRunner.query(`CREATE TYPE "public"."workout_plans_level_enum" AS ENUM('beginner', 'intermediate', 'advanced')`);
        await queryRunner.query(`CREATE TABLE "workout_plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "goal" "public"."workout_plans_goal_enum" NOT NULL DEFAULT 'hypertrophy', "level" "public"."workout_plans_level_enum" NOT NULL DEFAULT 'beginner', "user_id" uuid, "is_template" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9ae1bdd02db446a7541e2e5b161" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."performance_logs_difficulty_feedback_enum" AS ENUM('easy', 'ok', 'hard')`);
        await queryRunner.query(`CREATE TABLE "performance_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "workout_id" uuid NOT NULL, "exercise_id" uuid NOT NULL, "planned_sets" integer NOT NULL, "completed_sets" integer NOT NULL, "planned_reps" integer NOT NULL, "completed_reps" integer NOT NULL, "weight_used" numeric(5,2), "fatigue_rating" integer NOT NULL, "difficulty_feedback" "public"."performance_logs_difficulty_feedback_enum" NOT NULL, "skipped" boolean NOT NULL DEFAULT false, "date" date NOT NULL, CONSTRAINT "PK_75fdbcc18d181201a23de58f130" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b6b063e61b58fc5aec59003602" ON "performance_logs"  ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_adc5878451f04447188512c774" ON "performance_logs"  ("workout_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7d47e3db09299a98893a18d765" ON "performance_logs"  ("exercise_id") `);
        await queryRunner.query(`CREATE TABLE "water_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "date" date NOT NULL DEFAULT ('now'::text)::date, "amount" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7793241dc433ad0ac30ec9a906e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "body_metric_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "date" date NOT NULL DEFAULT ('now'::text)::date, "weight" numeric(5,2) NOT NULL, "body_fat_percentage" numeric(5,2), "skeletal_muscle_mass" numeric(5,2), "waist" numeric(5,2), "chest" numeric(5,2), "shoulders" numeric(5,2), "left_bicep" numeric(5,2), "right_bicep" numeric(5,2), "left_thigh" numeric(5,2), "right_thigh" numeric(5,2), "neck" numeric(5,2), "hips" numeric(5,2), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_aafe2c54f66ceaa743dc764c2df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."progress_photos_angle_enum" AS ENUM('front', 'side', 'back')`);
        await queryRunner.query(`CREATE TABLE "progress_photos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "date" date NOT NULL DEFAULT ('now'::text)::date, "angle" "public"."progress_photos_angle_enum" NOT NULL DEFAULT 'front', "image_url" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5396497e4283c10ac55ad4c9e7e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "recipe_ingredients" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "recipe_id" uuid NOT NULL, "food_id" uuid, "custom_name" character varying, "amount" numeric(6,2) NOT NULL, "unit" character varying NOT NULL DEFAULT 'g', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8f15a314e55970414fc92ffb532" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."recipes_source_enum" AS ENUM('database', 'user', 'ai')`);
        await queryRunner.query(`CREATE TABLE "recipes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" text NOT NULL, "instructions" jsonb NOT NULL, "prep_time" integer NOT NULL DEFAULT '0', "cook_time" integer NOT NULL DEFAULT '0', "servings" integer NOT NULL DEFAULT '1', "image_url" character varying, "calories" numeric(6,2) NOT NULL DEFAULT '0', "protein" numeric(5,2) NOT NULL DEFAULT '0', "carbs" numeric(5,2) NOT NULL DEFAULT '0', "fat" numeric(5,2) NOT NULL DEFAULT '0', "source" "public"."recipes_source_enum" NOT NULL DEFAULT 'database', "tags" jsonb NOT NULL DEFAULT '[]', "creator_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8f09680a51bf3669c1598a21682" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "recipe_external_mappings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "recipe_id" uuid NOT NULL, "provider_name" character varying NOT NULL, "external_id" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_802ddf3d42bfb9eb006b721840c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e288cbad7b4cf9a03ed87a38c3" ON "recipe_external_mappings"  ("provider_name", "external_id") `);
        await queryRunner.query(`CREATE TABLE "recipe_import_jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "provider_name" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "total_records" integer NOT NULL DEFAULT '0', "imported_records" integer NOT NULL DEFAULT '0', "failed_records" integer NOT NULL DEFAULT '0', "duplicate_records" integer NOT NULL DEFAULT '0', "error" text, "logs" jsonb NOT NULL DEFAULT '[]', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_51c6e59ae78bf3cd903d51400b0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."run_sessions_activitytype_enum" AS ENUM('run', 'walk', 'cycling', 'hiking')`);
        await queryRunner.query(`CREATE TABLE "run_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "title" character varying NOT NULL DEFAULT 'Outdoor Run', "activityType" "public"."run_sessions_activitytype_enum" NOT NULL DEFAULT 'run', "start_time" TIMESTAMP NOT NULL, "end_time" TIMESTAMP NOT NULL, "duration_seconds" integer NOT NULL, "distance_km" numeric(8,2) NOT NULL, "avg_pace_min_per_km" numeric(8,2), "calories_burned" integer, "route_coordinates" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_81f7861032f4e25454daa4e01e4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."step_intervals_source_enum" AS ENUM('sensor', 'manual')`);
        await queryRunner.query(`CREATE TABLE "step_intervals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "start_time" TIMESTAMP NOT NULL, "end_time" TIMESTAMP NOT NULL, "steps" integer NOT NULL, "source" "public"."step_intervals_source_enum" NOT NULL DEFAULT 'sensor', "activity_name" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b4e934abe9ba5e719e70a787cee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "step_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "date" date NOT NULL, "total_steps" integer NOT NULL DEFAULT '0', "streak" integer NOT NULL DEFAULT '0', "target_steps" integer NOT NULL DEFAULT '8000', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_3ae2082bb0c682d2379be441b28" UNIQUE ("user_id", "date"), CONSTRAINT "PK_cbe0c64c1569da17de1b3b8ef4a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "exercise_secondary_muscles" ("exercise_id" uuid NOT NULL, "muscle_group_id" uuid NOT NULL, CONSTRAINT "PK_da50b4ff5576a4e221ac106c75d" PRIMARY KEY ("exercise_id", "muscle_group_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7a64fabc5539bf8996ce1c5ab8" ON "exercise_secondary_muscles"  ("exercise_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d331a8451be37f01760cb558f5" ON "exercise_secondary_muscles"  ("muscle_group_id") `);
        await queryRunner.query(`ALTER TABLE "program_day_exercises" ADD CONSTRAINT "FK_92fb43a68b64048afdf74cf3c43" FOREIGN KEY ("program_day_id") REFERENCES "program_days"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "program_day_exercises" ADD CONSTRAINT "FK_b492afa3b5fb344f28960ed7ead" FOREIGN KEY ("exercise_id") REFERENCES "exercises"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "program_days" ADD CONSTRAINT "FK_d169b148b1edf17e0931a1252a0" FOREIGN KEY ("program_id") REFERENCES "programs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "profiles" ADD CONSTRAINT "FK_9e432b7df0d182f8d292902d1a2" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "profiles" ADD CONSTRAINT "FK_4b2906407dd41eb304431bce21c" FOREIGN KEY ("current_program_id") REFERENCES "programs"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workout_sessions" ADD CONSTRAINT "FK_3a1ec9260afc530837db15579a5" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workout_sessions" ADD CONSTRAINT "FK_41f52307a9a2ff3677a05164476" FOREIGN KEY ("program_day_id") REFERENCES "program_days"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exercise_logs" ADD CONSTRAINT "FK_626bfc99aebda502edb664bda91" FOREIGN KEY ("workout_session_id") REFERENCES "workout_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exercise_logs" ADD CONSTRAINT "FK_6af3b16426363ad9520c06b8f5d" FOREIGN KEY ("exercise_id") REFERENCES "exercises"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exercises" ADD CONSTRAINT "FK_c59c2449117e119e4ee8cbebe47" FOREIGN KEY ("muscle_group_id") REFERENCES "muscle_groups"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exercises" ADD CONSTRAINT "FK_2bb208f4a02f1b077c67352fc11" FOREIGN KEY ("equipment_id") REFERENCES "equipment"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nutrition_logs" ADD CONSTRAINT "FK_5f014ded97166b5596ba790100e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nutrition_logs" ADD CONSTRAINT "FK_35cd736f8dd909895f5376fc6bd" FOREIGN KEY ("food_id") REFERENCES "foods"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "foods" ADD CONSTRAINT "FK_c09f752a4673a3a1f338aa017ef" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workout_exercises" ADD CONSTRAINT "FK_d7cfe2372e71da68eddcf4940ee" FOREIGN KEY ("workout_plan_id") REFERENCES "workout_plans"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workout_exercises" ADD CONSTRAINT "FK_9a0656f321d9a96de2eb685e85a" FOREIGN KEY ("exercise_id") REFERENCES "exercises"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workout_plans" ADD CONSTRAINT "FK_d7fb89ee8bd7affdaa0d9963c3f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "performance_logs" ADD CONSTRAINT "FK_b6b063e61b58fc5aec59003602e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "performance_logs" ADD CONSTRAINT "FK_adc5878451f04447188512c774c" FOREIGN KEY ("workout_id") REFERENCES "workout_plans"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "performance_logs" ADD CONSTRAINT "FK_7d47e3db09299a98893a18d7654" FOREIGN KEY ("exercise_id") REFERENCES "exercises"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "water_logs" ADD CONSTRAINT "FK_2042e6d9e9f0b0178f12e27afe0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "body_metric_logs" ADD CONSTRAINT "FK_5e30fba5e25784f967fb896d790" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "progress_photos" ADD CONSTRAINT "FK_2ab828794cb4725415334c0cb6e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recipe_ingredients" ADD CONSTRAINT "FK_f240137e0e13bed80bdf64fed53" FOREIGN KEY ("recipe_id") REFERENCES "recipes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recipe_ingredients" ADD CONSTRAINT "FK_9f441dc9f69622084db183ccd2e" FOREIGN KEY ("food_id") REFERENCES "foods"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recipes" ADD CONSTRAINT "FK_8188b330b79f353885e77b9b14a" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recipe_external_mappings" ADD CONSTRAINT "FK_885740734bc4550b4a492f700ad" FOREIGN KEY ("recipe_id") REFERENCES "recipes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "run_sessions" ADD CONSTRAINT "FK_2508916ea3ffaa9f944883736ed" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "step_intervals" ADD CONSTRAINT "FK_a9cecf1be2af4861fe46eb722fc" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "step_logs" ADD CONSTRAINT "FK_e5d00af6b240a9e2a2bc9a207cc" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exercise_secondary_muscles" ADD CONSTRAINT "FK_7a64fabc5539bf8996ce1c5ab83" FOREIGN KEY ("exercise_id") REFERENCES "exercises"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "exercise_secondary_muscles" ADD CONSTRAINT "FK_d331a8451be37f01760cb558f5a" FOREIGN KEY ("muscle_group_id") REFERENCES "muscle_groups"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "exercise_secondary_muscles" DROP CONSTRAINT "FK_d331a8451be37f01760cb558f5a"`);
        await queryRunner.query(`ALTER TABLE "exercise_secondary_muscles" DROP CONSTRAINT "FK_7a64fabc5539bf8996ce1c5ab83"`);
        await queryRunner.query(`ALTER TABLE "step_logs" DROP CONSTRAINT "FK_e5d00af6b240a9e2a2bc9a207cc"`);
        await queryRunner.query(`ALTER TABLE "step_intervals" DROP CONSTRAINT "FK_a9cecf1be2af4861fe46eb722fc"`);
        await queryRunner.query(`ALTER TABLE "run_sessions" DROP CONSTRAINT "FK_2508916ea3ffaa9f944883736ed"`);
        await queryRunner.query(`ALTER TABLE "recipe_external_mappings" DROP CONSTRAINT "FK_885740734bc4550b4a492f700ad"`);
        await queryRunner.query(`ALTER TABLE "recipes" DROP CONSTRAINT "FK_8188b330b79f353885e77b9b14a"`);
        await queryRunner.query(`ALTER TABLE "recipe_ingredients" DROP CONSTRAINT "FK_9f441dc9f69622084db183ccd2e"`);
        await queryRunner.query(`ALTER TABLE "recipe_ingredients" DROP CONSTRAINT "FK_f240137e0e13bed80bdf64fed53"`);
        await queryRunner.query(`ALTER TABLE "progress_photos" DROP CONSTRAINT "FK_2ab828794cb4725415334c0cb6e"`);
        await queryRunner.query(`ALTER TABLE "body_metric_logs" DROP CONSTRAINT "FK_5e30fba5e25784f967fb896d790"`);
        await queryRunner.query(`ALTER TABLE "water_logs" DROP CONSTRAINT "FK_2042e6d9e9f0b0178f12e27afe0"`);
        await queryRunner.query(`ALTER TABLE "performance_logs" DROP CONSTRAINT "FK_7d47e3db09299a98893a18d7654"`);
        await queryRunner.query(`ALTER TABLE "performance_logs" DROP CONSTRAINT "FK_adc5878451f04447188512c774c"`);
        await queryRunner.query(`ALTER TABLE "performance_logs" DROP CONSTRAINT "FK_b6b063e61b58fc5aec59003602e"`);
        await queryRunner.query(`ALTER TABLE "workout_plans" DROP CONSTRAINT "FK_d7fb89ee8bd7affdaa0d9963c3f"`);
        await queryRunner.query(`ALTER TABLE "workout_exercises" DROP CONSTRAINT "FK_9a0656f321d9a96de2eb685e85a"`);
        await queryRunner.query(`ALTER TABLE "workout_exercises" DROP CONSTRAINT "FK_d7cfe2372e71da68eddcf4940ee"`);
        await queryRunner.query(`ALTER TABLE "foods" DROP CONSTRAINT "FK_c09f752a4673a3a1f338aa017ef"`);
        await queryRunner.query(`ALTER TABLE "nutrition_logs" DROP CONSTRAINT "FK_35cd736f8dd909895f5376fc6bd"`);
        await queryRunner.query(`ALTER TABLE "nutrition_logs" DROP CONSTRAINT "FK_5f014ded97166b5596ba790100e"`);
        await queryRunner.query(`ALTER TABLE "exercises" DROP CONSTRAINT "FK_2bb208f4a02f1b077c67352fc11"`);
        await queryRunner.query(`ALTER TABLE "exercises" DROP CONSTRAINT "FK_c59c2449117e119e4ee8cbebe47"`);
        await queryRunner.query(`ALTER TABLE "exercise_logs" DROP CONSTRAINT "FK_6af3b16426363ad9520c06b8f5d"`);
        await queryRunner.query(`ALTER TABLE "exercise_logs" DROP CONSTRAINT "FK_626bfc99aebda502edb664bda91"`);
        await queryRunner.query(`ALTER TABLE "workout_sessions" DROP CONSTRAINT "FK_41f52307a9a2ff3677a05164476"`);
        await queryRunner.query(`ALTER TABLE "workout_sessions" DROP CONSTRAINT "FK_3a1ec9260afc530837db15579a5"`);
        await queryRunner.query(`ALTER TABLE "profiles" DROP CONSTRAINT "FK_4b2906407dd41eb304431bce21c"`);
        await queryRunner.query(`ALTER TABLE "profiles" DROP CONSTRAINT "FK_9e432b7df0d182f8d292902d1a2"`);
        await queryRunner.query(`ALTER TABLE "program_days" DROP CONSTRAINT "FK_d169b148b1edf17e0931a1252a0"`);
        await queryRunner.query(`ALTER TABLE "program_day_exercises" DROP CONSTRAINT "FK_b492afa3b5fb344f28960ed7ead"`);
        await queryRunner.query(`ALTER TABLE "program_day_exercises" DROP CONSTRAINT "FK_92fb43a68b64048afdf74cf3c43"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d331a8451be37f01760cb558f5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a64fabc5539bf8996ce1c5ab8"`);
        await queryRunner.query(`DROP TABLE "exercise_secondary_muscles"`);
        await queryRunner.query(`DROP TABLE "step_logs"`);
        await queryRunner.query(`DROP TABLE "step_intervals"`);
        await queryRunner.query(`DROP TYPE "public"."step_intervals_source_enum"`);
        await queryRunner.query(`DROP TABLE "run_sessions"`);
        await queryRunner.query(`DROP TYPE "public"."run_sessions_activitytype_enum"`);
        await queryRunner.query(`DROP TABLE "recipe_import_jobs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e288cbad7b4cf9a03ed87a38c3"`);
        await queryRunner.query(`DROP TABLE "recipe_external_mappings"`);
        await queryRunner.query(`DROP TABLE "recipes"`);
        await queryRunner.query(`DROP TYPE "public"."recipes_source_enum"`);
        await queryRunner.query(`DROP TABLE "recipe_ingredients"`);
        await queryRunner.query(`DROP TABLE "progress_photos"`);
        await queryRunner.query(`DROP TYPE "public"."progress_photos_angle_enum"`);
        await queryRunner.query(`DROP TABLE "body_metric_logs"`);
        await queryRunner.query(`DROP TABLE "water_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d47e3db09299a98893a18d765"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_adc5878451f04447188512c774"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b6b063e61b58fc5aec59003602"`);
        await queryRunner.query(`DROP TABLE "performance_logs"`);
        await queryRunner.query(`DROP TYPE "public"."performance_logs_difficulty_feedback_enum"`);
        await queryRunner.query(`DROP TABLE "workout_plans"`);
        await queryRunner.query(`DROP TYPE "public"."workout_plans_level_enum"`);
        await queryRunner.query(`DROP TYPE "public"."workout_plans_goal_enum"`);
        await queryRunner.query(`DROP TABLE "workout_exercises"`);
        await queryRunner.query(`DROP TABLE "foods"`);
        await queryRunner.query(`DROP TYPE "public"."foods_source_enum"`);
        await queryRunner.query(`DROP TABLE "nutrition_logs"`);
        await queryRunner.query(`DROP TYPE "public"."nutrition_logs_mealtype_enum"`);
        await queryRunner.query(`DROP TABLE "exercises"`);
        await queryRunner.query(`DROP TYPE "public"."exercises_source_enum"`);
        await queryRunner.query(`DROP TYPE "public"."exercises_difficulty_enum"`);
        await queryRunner.query(`DROP TABLE "muscle_groups"`);
        await queryRunner.query(`DROP TABLE "exercise_logs"`);
        await queryRunner.query(`DROP TABLE "workout_sessions"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "profiles"`);
        await queryRunner.query(`DROP TYPE "public"."profiles_equipment_access_enum"`);
        await queryRunner.query(`DROP TYPE "public"."profiles_fitness_level_enum"`);
        await queryRunner.query(`DROP TYPE "public"."profiles_goal_enum"`);
        await queryRunner.query(`DROP TABLE "programs"`);
        await queryRunner.query(`DROP TYPE "public"."programs_level_enum"`);
        await queryRunner.query(`DROP TABLE "program_days"`);
        await queryRunner.query(`DROP TABLE "program_day_exercises"`);
        await queryRunner.query(`DROP TABLE "equipment"`);
    }

}
